import HeaderComponent from 'components/headerComponent';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Insta Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <HeaderComponent />

      {/* Feed */}

      {/* Modal */}
    </div>
  );
}
